version: '3.8'

services:
  headscale-ui:
    build: .
    container_name: headscale-ui
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - HEADSCALE_URL=${HEADSCALE_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 